#!/bin/sh

echo "🔍 Running fast checks before commit..."

# Форматирование и линтинг только стейджнутых файлов
npx lint-staged || (echo '❌ Lint-staged failed'; false)

echo "✅ Pre-commit checks passed."