name: 🚀 Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: root
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /opt/petly-front
            git config pull.rebase false
            git pull origin main
            docker compose stop frontend
            docker compose rm -f frontend
            docker rmi $(docker images -q --filter=reference='*frontend*') || true
            docker compose up -d --build --pull always frontend
