name: 🚀 Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        run: echo "${{ github.token }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build & Push Docker image
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/petly-front:latest
          docker build -t $IMAGE .
          docker push $IMAGE

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: root
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            cd /opt/petly
            docker compose pull front
            docker compose up -d front
            docker exec nginx nginx -s reload || true
